In [4]:
#Import the necessary libraries
import re
import string 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from plotly import graph_objs as go
import nltk
import warnings
warnings.filterwarnings("ignore")
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
from collections import Counter

The following is a good example to see how tokenizing, stemming and removal of stopwords actually works

In [5]:
my_text="I walked to the shop and found out that he had dashed to the Mall just before I got there. I dont like catching up with him that much though.Maybe I'm not friendly. He is somehow a stranger to me"

In [6]:
my_text=str(my_text).lower()

In [7]:
#tokenize to sentences
my_sent=nltk.sent_tokenize(my_text)
stemmer=PorterStemmer()

In [8]:
print(my_sent)

['i walked to the shop and found out that he had dashed to the mall just before i got there.', "i dont like catching up with him that much though.maybe i'm not friendly.", 'he is somehow a stranger to me']


In [9]:
#tokenize to words
my_words=word_tokenize(my_text)

In [10]:
print(my_words)

['i', 'walked', 'to', 'the', 'shop', 'and', 'found', 'out', 'that', 'he', 'had', 'dashed', 'to', 'the', 'mall', 'just', 'before', 'i', 'got', 'there', '.', 'i', 'dont', 'like', 'catching', 'up', 'with', 'him', 'that', 'much', 'though.maybe', 'i', "'m", 'not', 'friendly', '.', 'he', 'is', 'somehow', 'a', 'stranger', 'to', 'me']


In [11]:
#remove stopwords and stem
for i in range(len(my_words)):
    outword=[stemmer.stem(word) for word in my_words if word not in set(stopwords.words("english"))]
  

In [12]:
print(outword)

['walk', 'shop', 'found', 'dash', 'mall', 'got', '.', 'dont', 'like', 'catch', 'much', 'though.mayb', "'m", 'friendli', '.', 'somehow', 'stranger']


In [13]:
#remove stopwords and lemmatize
lemmatizer=WordNetLemmatizer()
for i in range(len(my_words)):
    lem_word=[lemmatizer.lemmatize(word) for word in my_words if word not in set(stopwords.words("english"))]

In [14]:
print(lem_word)
print(len(lem_word))

['walked', 'shop', 'found', 'dashed', 'mall', 'got', '.', 'dont', 'like', 'catching', 'much', 'though.maybe', "'m", 'friendly', '.', 'somehow', 'stranger']
17


In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [16]:
bow=cv.fit_transform(lem_word).toarray()

In [17]:
print(np.matrix(bow))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]


In [19]:
bow.shape

(17, 15)

# TF-IDF Model

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()
tf=cv.fit_transform(df_bow['text_lem']).toarray

In [ ]:
print(np.matrix(tf))

In [ ]:
tf.shape